services:
    rstudio:
        build:
            context: .
        environment:
            - TZ=Europe/Madrid
            - DISABLE_AUTH=true
            - PYTHONUSERBASE=/home/rstudio/.cache/pip
            - JULIA_DEPOT_PATH=/home/rstudio/.cache/julia
        volumes:
            - .:/home/rstudio/work
            - cache:/home/rstudio/.cache
            - TinyTeX:/home/rstudio/.TinyTeX
            - fonts:/usr/share/fonts
volumes:
  cache:
    external: true
  TinyTeX:
    external: true
  fonts:
    external: true